// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6sE6CRRBkKUxWSwwsW8HeuT60KRFXEE',
    appId: '1:349930269675:web:f4ab1db9ed6f23d86a47ae',
    messagingSenderId: '349930269675',
    projectId: 'second-hand-store-e2539',
    authDomain: 'second-hand-store-e2539.firebaseapp.com',
    storageBucket: 'second-hand-store-e2539.appspot.com',
    measurementId: 'G-Y1768LJBDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13O08Ptl1WiDSGYEzbuV1CEdipF5NhBo',
    appId: '1:349930269675:android:93262deea5c594f76a47ae',
    messagingSenderId: '349930269675',
    projectId: 'second-hand-store-e2539',
    storageBucket: 'second-hand-store-e2539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQAtGoLldoW9MrIOgMC4v-6ReFPDuxN-Y',
    appId: '1:349930269675:ios:8a7ff3ca3875d8f06a47ae',
    messagingSenderId: '349930269675',
    projectId: 'second-hand-store-e2539',
    storageBucket: 'second-hand-store-e2539.appspot.com',
    iosClientId: '349930269675-e57v1ipaqrt5dg6q8b31hilq3oo01en8.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondHandStore',
  );
}
